version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            database: cost-explorer-db
            user: root
            password: prisma
            rawAccess: true
            port: '3306'
            migrations: false
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: cost-explorer-db
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~